import './globals.css'
import { Inter } from 'next/font/google'
import { ThemeWrapper } from './providers';
import ThemeToggler from './components/ThemeToggler';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className + ``}>
        <ThemeWrapper >
          <div className='absolute right-8 top-4' >
            <ThemeToggler></ThemeToggler>
          </div>
          {children}

        </ThemeWrapper>
      </body>
    </html>
  )
}


